assetDir                        = "computer-techniques/assets"
baseurl                         = "https://kylehugh.es/"
contentDir                      = "computer-techniques/content"
dataDir                         = "computer-techniques/data"
disableKinds                    = ["RSS", "taxonomy", "taxonomyTerm", "section"]
enableGitInfo                   = true
languageCode                    = "en-us"
layoutDir                       = "computer-techniques/layouts"
publishDir                      = "build"
staticDir                       = "computer-techniques/static"
title                           = "Computer Techniques"
uglyurls                        = false

[Author]  
    name                        = "Kyle Hughes" 
    twitter                     = "KyleHughes"

[params]
    description                 = "How to use computers professionally and recreationally."

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = 4